const categories = [
    {
        name: 'Furniture',
        id: 'Furniture',
        subcategories: [
            { name: 'Sofas', id: 'Sofas' },
            { name: 'Tables', id: 'Tables' },
            { name: 'Chairs', id: 'Chairs' },
            { name: 'Bedsides', id: 'Bedsides' }
        ]
    },
    {
        name: 'Accessories',
        id: 'Accessories',
        subcategories: [
            { name: 'Cushions', id: 'Cushions' },
            { name: 'Lamps', id: 'Lamps' }
        ]
    },
    {
        name: 'Decor',
        id: 'Decor',
        subcategories: [
            { name: 'Vases', id: 'Vases' },
            { name: 'Baskets', id: 'Baskets' },
            { name: 'Bowls', id: 'Bowls' }
        ]
    },
    {
        name: 'Textile',
        id: 'Textile',
        subcategories: [
            { name: 'Tablecloths', id: 'Tablecloths' }
        ]
    }
];

const products = [
    { id: 'SKU-1000', 
        imgSrc: 'images/single-img-1.jpg', 
        name: 'Minimal 954', 
        description: 'Elegant single product perfect for any space.',
        offer: 'Buy Now', 
        price: 250, 
        colors: ['burlywood', 'olive', 'darkred'], 
        special: 'single', 
        category: 'Furniture', 
        subcategory: 'Sofas', 
        dimensions: [{ height: 80, weight: 10, depth: 90 }, { height: 85, weight: 12, depth: 95 }], 
        specifications: { assembly: 'Easy', care: 'Wipe clean', material: 'Wood' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 10 }, { branch: 'Store A', address: '456 Elm St', quantity: 5 }] },
    { id: 'SKU-2000', 
        imgSrc: 'images/sofa-1.jpg', 
        name: 'Safari 900', 
        description: 'Comfortable sofa with modern design.',
        offer: 'Buy Now', 
        price: 1500, 
        colors: ['lightgray', 'olive'], 
        special: 'single', 
        category: 'Furniture', 
        subcategory: 'Sofas', 
        dimensions: [{ height: 90, weight: 30, depth: 100 }, { height: 95, weight: 32, depth: 105 }], 
        specifications: { assembly: 'Professional', care: 'Vacuum regularly', material: 'Fabric' }, 
        availability: [{ branch: 'Store A', address: '456 Elm St', quantity: 5 }, { branch: 'Store B', address: '789 Oak St', quantity: 8 }] },
    { id: 'SKU-3000', 
        imgSrc: 'images/photo-1565031491910-e57fac031c41.jpg', 
        name: 'Gwen 968', 
        description: 'Stylish single item to enhance your home.',
        offer: 'Sale %30', 
        price: 400, 
        colors: [], 
        special: 'single', 
        category: 'Furniture', 
        subcategory: 'Sofas', 
        dimensions: [{ height: 85, weight: 20, depth: 85 }], 
        specifications: { assembly: 'Minimal', care: 'Dust with a dry cloth', material: 'Leather' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 7 }] },
    { id: 'SKU-4000', 
        imgSrc: 'images/photo-1606744824163-985d376605aa.avif', 
        name: 'Grace 110', 
        description: 'Unique single piece for contemporary interiors.',
        offer: 'Sale %15', 
        price: 600, 
        colors: [], 
        special: 'single', 
        category: 'Furniture', 
        subcategory: 'Chairs', 
        dimensions: [{ height: 100, weight: 15, depth: 55 }, { height: 105, weight: 17, depth: 60 }], 
        specifications: { assembly: 'Easy', care: 'Clean with a damp cloth', material: 'Metal' }, 
        availability: [{ branch: 'Store B', address: '789 Oak St', quantity: 6 }] },
    { id: 'SKU-5000', 
        imgSrc: 'images/table.jpg', 
        name: 'Zana 131', 
        description: 'Modern and sleek single product for any decor.',
        offer: 'Sale %25', 
        price: 800, 
        colors: [], 
        special: 'single', 
        category: 'Furniture', 
        subcategory: 'Tables', 
        dimensions: [{ height: 75, weight: 20, depth: 120 }, { height: 80, weight: 22, depth: 125 }], 
        specifications: { assembly: 'Assembly required', care: 'Wipe with a damp cloth', material: 'Glass' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 4 }, { branch: 'Store A', address: '456 Elm St', quantity: 3 }] },
    { id: 'SKU-6000', 
        imgSrc: 'images/photo-1618221195710-dd6b41faaea6.avif', 
        name: 'Terra 686', 
        description: 'Chic single piece with a stylish touch.',
        offer: 'Buy Now', 
        price: 350, 
        colors: [], 
        special: 'single', 
        category: 'Furniture', 
        subcategory: 'Tables', 
        dimensions: [{ height: 80, weight: 18, depth: 100 }], 
        specifications: { assembly: 'Minimal', care: 'Dust regularly', material: 'Wood' }, availability: [{ branch: 'Store C', address: '101 Pine St', quantity: 5 }] },
    { id: 'SKU-7000', 
        imgSrc: 'images/photo-1549187774-b4e9b0445b41.avif', 
        name: 'York 775', 
        description: 'Trendy single item for contemporary spaces.',
        offer: 'Sale %15', 
        price: 500, 
        colors: [], 
        special: 'single', 
        category: 'Furniture', 
        subcategory: 'Sofas', 
        dimensions: [{ height: 85, weight: 22, depth: 95 }, { height: 90, weight: 24, depth: 100 }], 
        specifications: { assembly: 'Professional', care: 'Vacuum regularly', material: 'Fabric' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 8 }, { branch: 'Store B', address: '789 Oak St', quantity: 6 }] },
    { id: 'SKU-8000', 
        imgSrc: 'images/chair.avif', 
        name: 'Beudje 905', 
        description: 'Comfortable chair set for modern homes.',
        offer: 'Sale 25%', 
        price: 1200, 
        colors: ['burlywood', 'red', 'peru'], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Chairs', 
        dimensions: [{ height: 95, weight: 12, depth: 55 }, { height: 100, weight: 14, depth: 60 }], 
        specifications: { assembly: 'Easy', care: 'Wipe clean', material: 'Leather' }, 
        availability: [{ branch: 'Store A', address: '456 Elm St', quantity: 7 }, { branch: 'Store C', address: '101 Pine St', quantity: 4 }] },
    { id: 'SKU-9000', 
        imgSrc: 'images/chair4.avif', 
        name: 'Origin 901', 
        description: 'Stylish chairs that complement any decor.',
        offer: 'Buy Now', 
        price: 1500, 
        colors: [], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Chairs', 
        dimensions: [{ height: 100, weight: 14, depth: 60 }, { height: 105, weight: 16, depth: 65 }], 
        specifications: { assembly: 'Professional', care: 'Dust with a dry cloth', material: 'Metal' }, 
        availability: [{ branch: 'Store B', address: '789 Oak St', quantity: 6 }, { branch: 'Store C', address: '101 Pine St', quantity: 3 }] },
    { id: 'SKU-10000', 
        imgSrc: 'images/bascket.jpg', 
        name: 'Marocco 95', 
        description: 'Functional and decorative basket set.',
        offer: 'Sale 15%',
        price: 60, 
        colors: [],
        special: 'set', 
        category: 'Decor', 
        subcategory: 'Baskets', 
        dimensions: [{ height: 30, weight: 5, depth: 30 }], 
        specifications: { assembly: 'None', care: 'Wipe clean', material: 'Wicker' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 12 }] },
    { id: 'SKU-1100', 
        imgSrc: 'images/bedside.jpg', 
        name: 'Retro 707', 
        description: 'Elegant bedside table set for your bedroom.',
        offer: 'Buy Now', 
        price: 200, 
        colors: [], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Bedsides', 
        dimensions: [{ height: 60, weight: 8, depth: 40 }, { height: 65, weight: 9, depth: 45 }], 
        specifications: { assembly: 'Easy', care: 'Dust regularly', material: 'Wood' }, availability: [{ branch: 'Store A', address: '456 Elm St', quantity: 8 }] },
    { id: 'SKU-1200', 
        imgSrc: 'images/chair2.avif', 
        name: 'Kvela 988', 
        description: 'Modern chair set for any living area.',
        offer: 'Sale 15%', 
        price: 900, 
        colors: [], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Chairs', 
        dimensions: [{ height: 95, weight: 12, depth: 55 }, { height: 100, weight: 14, depth: 60 }],
        specifications: { assembly: 'Easy', care: 'Wipe clean', material: 'Fabric' }, 
        availability: [{ branch: 'Store C', address: '101 Pine St', quantity: 6 }] },
    { id: 'SKU-1300', 
        imgSrc: 'images/coffe-table.jpg', 
        name: 'Chrome 101', 
        description: 'Chic coffee table set to enhance your living space.',
        offer: 'Sale 30%', 
        price: 400, 
        colors: [], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Tables', 
        dimensions: [{ height: 45, weight: 15, depth: 80 }, { height: 50, weight: 17, depth: 85 }], 
        specifications: { assembly: 'Assembly required', care: 'Wipe with a damp cloth', material: 'Metal' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 5 }, { branch: 'Store A', address: '456 Elm St', quantity: 3 }] },
    { id: 'SKU-1400', 
        imgSrc: 'images/chair3.avif', 
        name: 'Blanko 001', 
        description: 'Stylish chair set for contemporary interiors.',
        offer: 'Buy Now', 
        price: 1300, 
        colors: ['black', 'cornsilk'],
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Chairs', 
        dimensions: [{ height: 100, weight: 14, depth: 60 }, { height: 105, weight: 16, depth: 65 }], 
        specifications: { assembly: 'Professional', care: 'Dust regularly', material: 'Leather' }, 
        availability: [{ branch: 'Store A', address: '456 Elm St', quantity: 8 }, { branch: 'Store B', address: '789 Oak St', quantity: 5 }] },
    { id: 'SKU-1500', 
        imgSrc: 'images/pillow-1.jpg', 
        name: 'Sandy 303', 
        description: 'Decorative pillow set for comfort and style.',
        offer: 'Buy Now', 
        price: 80, 
        colors: ['lightgray', 'olive', 'cornsilk', 'burlywood'], 
        special: 'set', 
        category: 'Accessories', 
        subcategory: 'Cushions', 
        dimensions: [{ height: 40, weight: 1, depth: 40 }], 
        specifications: { assembly: 'None', care: 'Spot clean', material: 'Cotton' }, 
        availability: [{ branch: 'Store C', address: '101 Pine St', quantity: 15 }] },
    { id: 'SKU-1600', 
        imgSrc: 'images/chair5.jpg', 
        name: 'Greko 383', 
        description: 'Elegant chair set with a modern design.',
        offer: 'Buy Now', 
        price: 1400, 
        colors: ['olive', 'darkred', 'peru'], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Chairs', 
        dimensions: [{ height: 95, weight: 14, depth: 55 }, { height: 100, weight: 16, depth: 60 }], 
        specifications: { assembly: 'Easy', care: 'Wipe clean', material: 'Wood' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 5 }, { branch: 'Store B', address: '789 Oak St', quantity: 7 }] },
    { id: 'SKU-1700', 
        imgSrc: 'images/sofa-grey-half.jpg', 
        name: 'CRO 909', 
        description: 'Comfortable sofa set for any living room.',
        offer: 'Sale 15%', 
        price: 2500, 
        colors: ['lightgray', 'olive', 'darkred', 'peru'], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Sofas', 
        dimensions: [{ height: 90, weight: 40, depth: 100 }, { height: 95, weight: 42, depth: 105 }], 
        specifications: { assembly: 'Professional', care: 'Vacuum regularly', material: 'Fabric' }, 
        availability: [{ branch: 'Store A', address: '456 Elm St', quantity: 4 }, { branch: 'Store C', address: '101 Pine St', quantity: 2 }] },
    { id: 'SKU-1800', 
        imgSrc: 'images/vase4.jpg', 
        name: 'Murel 707', 
        description: 'Decorative vase set for a stylish touch.',
        offer: 'Sale 25%', 
        price: 90, 
        colors: [], 
        special: 'set', 
        category: 'Decor', 
        subcategory: 'Vases', 
        dimensions: [{ height: 30, weight: 2, depth: 30 }], 
        specifications: { assembly: 'None', care: 'Wipe clean', material: 'Ceramic' }, 
        availability: [{ branch: 'Store B', address: '789 Oak St', quantity: 8 }] },
    { id: 'SKU-1900', 
        imgSrc: 'images/pillow.avif', 
        name: 'Soho 353', 
        description: 'Soft and cozy pillow set for any space.',
        offer: 'Buy Now', 
        price: 70, 
        colors: [], 
        special: 'set', 
        category: 'Accessories', 
        subcategory: 'Cushions', 
        dimensions: [{ height: 40, weight: 1, depth: 40 }], 
        specifications: { assembly: 'None', care: 'Spot clean', material: 'Polyester' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 10 }, { branch: 'Store A', address: '456 Elm St', quantity: 5 }] },
    { id: 'SKU-2000', 
        imgSrc: 'images/chair6.jpg', 
        name: 'Amer 030', 
        description: 'Stylish and comfortable chair set.',
        offer: 'Sale 10%', 
        price: 1600, 
        colors: [], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Chairs', 
        dimensions: [{ height: 100, weight: 16, depth: 60 }, { height: 105, weight: 18, depth: 65 }], 
        specifications: { assembly: 'Professional', care: 'Dust with a dry cloth', material: 'Leather' }, 
        availability: [{ branch: 'Store A', address: '456 Elm St', quantity: 7 }, { branch: 'Store C', address: '101 Pine St', quantity: 5 }] },
    { id: 'SKU-2100', 
        imgSrc: 'images/vase5.avif', 
        name: 'Stela 050', 
        description: 'Elegant vase set to enhance your decor.',
        offer: 'Sale 25%', 
        price: 120, 
        colors: [], 
        special: 'set', 
        category: 'Decor', 
        subcategory: 'Vases', 
        dimensions: [{ height: 35, weight: 3, depth: 35 }], 
        specifications: { assembly: 'None', care: 'Wipe clean', material: 'Glass' }, 
        availability: [{ branch: 'Store B', address: '789 Oak St', quantity: 6 }] },
    { id: 'SKU-2200', 
        imgSrc: 'images/chairs.avif', 
        name: 'Nutto 504', 
        description: 'Modern chair set for a fresh look.',
        offer: 'Buy Now', 
        price: 1100, 
        colors: ['darkred', 'black'], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Chairs', 
        dimensions: [{ height: 95, weight: 12, depth: 55 }, { height: 100, weight: 14, depth: 60 }], 
        specifications: { assembly: 'Easy', care: 'Wipe clean', material: 'Fabric' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 7 }, { branch: 'Store C', address: '101 Pine St', quantity: 5 }] },
    { id: 'SKU-2300', 
        imgSrc: 'images/vase.jpg', 
        name: 'Tuta 440', 
        description: 'Decorative vase set for adding elegance.',
        offer: 'Sale 15%', 
        price: 75, 
        colors: ['cornsilk', 'darkred', 'olive', 'peru'], 
        special: 'set', 
        category: 'Decor', 
        subcategory: 'Vases', 
        dimensions: [{ height: 25, weight: 2, depth: 25 }], 
        specifications: { assembly: 'None', care: 'Wipe clean', material: 'Ceramic' }, 
        availability: [{ branch: 'Store C', address: '101 Pine St', quantity: 9 }] },
    { id: 'SKU-2400', 
        imgSrc: 'images/coffe-table3.jpg', 
        name: 'Zino 080', 
        description: 'Functional coffee table set for modern homes.',
        offer: 'Buy Now', 
        price: 400, 
        colors: [], 
        special: 'set', 
        category: 'Furniture', 
        subcategory: 'Tables', 
        dimensions: [{ height: '50cm', weight: '15kg', depth: '100cm' }], 
        specifications: { assembly: 'Assembly required', care: 'Wipe with a damp cloth', material: 'Wood' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 5 }, { branch: 'Second Store', address: '456 Elm St', quantity: 3 }] },
    { id: 'SKU-2500', 
        imgSrc: 'images/lamp.jpg', 
        name: 'Fema 702', 
        description: 'Stylish lamp set to brighten up your space.',
        offer: 'Sale 15%', 
        price: 200, 
        colors: ['cornsilk', 'darkred', 'olive', 'peru'], 
        special: 'set', 
        category: 'Accessories', 
        subcategory: 'Lamps', 
        dimensions: [{ height: '30cm', weight: '3kg', depth: '15cm' }, { height: '40cm', weight: '4kg', depth: '20cm' }], 
        specifications: { assembly: 'No assembly required', care: 'Dust regularly', material: 'Metal and fabric' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 10 }] },
    { id: 'SKU-2600', 
        imgSrc: 'images/vase3.jpg', 
        name: 'Zwin 011', 
        description: 'Decorative vase set with a modern design.',
        offer: 'Sale 25%', 
        price: 100, 
        colors: ['cornsilk', 'lightgray'], 
        special: 'set', 
        category: 'Decor', 
        subcategory: 'Vases', 
        dimensions: [{ height: '20cm', weight: '1kg', depth: '10cm' }], 
        specifications: { assembly: 'No assembly required', care: 'Clean with a soft cloth', material: 'Ceramic' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 7 }, { branch: 'Second Store', address: '456 Elm St', quantity: 4 }] },
    { id: 'SKU-2700', 
        imgSrc: 'images/wood-bowl.avif', 
        name: 'XEE 455', 
        description: 'Unique wooden bowl set for a rustic touch.',
        offer: 'Sale 25%', 
        price: 150, 
        colors: [], 
        special: 'set', 
        category: 'Decor', 
        subcategory: 'Bowls', 
        dimensions: [{ height: '15cm', weight: '2kg', depth: '25cm' }, { height: '20cm', weight: '3kg', depth: '30cm' }], 
        specifications: { assembly: 'No assembly required', care: 'Wipe with a dry cloth', material: 'Wood' }, 
        availability: [{ branch: 'Main Store', address: '123 Main St', quantity: 8 }] 
    }
];